CREATE TABLE Fruit(Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Name VARCHAR(100) NOT NULL UNIQUE)

INSERT Fruit(Name) VALUES('Orange')
	, ('Apple')
	, ('Banana')

CREATE TABLE Price(Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, IdFruit INT NOT NULL, Value DECIMAL(18,2))
ALTER TABLE Price ADD CONSTRAINT FK_Price_Fruit FOREIGN KEY(IdFruit) REFERENCES Fruit(Id)