CREATE DATABASE [Test-001]
GO
CREATE DATABASE [Test-002]
GO
CREATE DATABASE [Test-003]
GO
CREATE DATABASE [Test-004]
GO
CREATE DATABASE [Test-005]
GO
CREATE DATABASE [Test-006]
GO
CREATE DATABASE [Test-007]
GO
CREATE DATABASE [Test-008]
GO
CREATE DATABASE [Test-009]
GO
CREATE DATABASE [Test-010]
GO
CREATE DATABASE [Test-011]
GO
CREATE DATABASE [Test-012]
GO
CREATE DATABASE [Test-013]
GO
CREATE DATABASE [Test-014]
GO
CREATE DATABASE [Test-015]
GO
CREATE DATABASE [Test-016]
GO
CREATE DATABASE [Test-017]
GO
CREATE DATABASE [Test-018]
GO
CREATE DATABASE [Test-019]
GO
CREATE DATABASE [Test-020]
GO
CREATE DATABASE [Test-021]
GO
CREATE DATABASE [Test-022]
GO
CREATE DATABASE [Test-023]
GO
CREATE DATABASE [Test-024]
GO
CREATE DATABASE [Test-025]
GO
CREATE DATABASE [Test-026]
GO
CREATE DATABASE [Test-027]
GO
CREATE DATABASE [Test-028]
GO
CREATE DATABASE [Test-029]
GO
CREATE DATABASE [Test-030]
GO
CREATE DATABASE [Test-031]
GO
CREATE DATABASE [Test-032]
GO
CREATE DATABASE [Test-033]
GO
CREATE DATABASE [Test-034]
GO
CREATE DATABASE [Test-035]
GO
CREATE DATABASE [Test-036]
GO
CREATE DATABASE [Test-037]
GO
CREATE DATABASE [Test-038]
GO
CREATE DATABASE [Test-039]
GO
CREATE DATABASE [Test-040]
GO
CREATE DATABASE [Test-041]
GO
CREATE DATABASE [Test-042]
GO
CREATE DATABASE [Test-043]
GO
CREATE DATABASE [Test-044]
GO
CREATE DATABASE [Test-045]
GO
CREATE DATABASE [Test-046]
GO
CREATE DATABASE [Test-047]
GO
CREATE DATABASE [Test-048]
GO
CREATE DATABASE [Test-049]
GO
CREATE DATABASE [Test-050]
GO
CREATE DATABASE [Test-051]
GO
CREATE DATABASE [Test-052]
GO
CREATE DATABASE [Test-053]
GO
CREATE DATABASE [Test-054]
GO
CREATE DATABASE [Test-055]
GO
CREATE DATABASE [Test-056]
GO
CREATE DATABASE [Test-057]
GO
CREATE DATABASE [Test-058]
GO
CREATE DATABASE [Test-059]
GO
CREATE DATABASE [Test-060]
GO
CREATE DATABASE [Test-061]
GO
CREATE DATABASE [Test-062]
GO
CREATE DATABASE [Test-063]
GO
CREATE DATABASE [Test-064]
GO
CREATE DATABASE [Test-065]
GO
CREATE DATABASE [Test-066]
GO
CREATE DATABASE [Test-067]
GO
CREATE DATABASE [Test-068]
GO
CREATE DATABASE [Test-069]
GO
CREATE DATABASE [Test-070]
GO
CREATE DATABASE [Test-071]
GO
CREATE DATABASE [Test-072]
GO
CREATE DATABASE [Test-073]
GO
CREATE DATABASE [Test-074]
GO
CREATE DATABASE [Test-075]
GO
CREATE DATABASE [Test-076]
GO
CREATE DATABASE [Test-077]
GO
CREATE DATABASE [Test-078]
GO
CREATE DATABASE [Test-079]
GO
CREATE DATABASE [Test-080]
GO
CREATE DATABASE [Test-081]
GO
CREATE DATABASE [Test-082]
GO
CREATE DATABASE [Test-083]
GO
CREATE DATABASE [Test-084]
GO
CREATE DATABASE [Test-085]
GO
CREATE DATABASE [Test-086]
GO
CREATE DATABASE [Test-087]
GO
CREATE DATABASE [Test-088]
GO
CREATE DATABASE [Test-089]
GO
CREATE DATABASE [Test-090]
GO
CREATE DATABASE [Test-091]
GO
CREATE DATABASE [Test-092]
GO
CREATE DATABASE [Test-093]
GO
CREATE DATABASE [Test-094]
GO
CREATE DATABASE [Test-095]
GO
CREATE DATABASE [Test-096]
GO
CREATE DATABASE [Test-097]
GO
CREATE DATABASE [Test-098]
GO
CREATE DATABASE [Test-099]
GO
CREATE DATABASE [Test-100]
GO
CREATE DATABASE [Test-101]
GO
CREATE DATABASE [Test-102]
GO
CREATE DATABASE [Test-103]
GO
CREATE DATABASE [Test-104]
GO
CREATE DATABASE [Test-105]
GO
CREATE DATABASE [Test-106]
GO
CREATE DATABASE [Test-107]
GO
CREATE DATABASE [Test-108]
GO
CREATE DATABASE [Test-109]
GO
CREATE DATABASE [Test-110]
GO
CREATE DATABASE [Test-111]
GO
CREATE DATABASE [Test-112]
GO
CREATE DATABASE [Test-113]
GO
CREATE DATABASE [Test-114]
GO
CREATE DATABASE [Test-115]
GO
CREATE DATABASE [Test-116]
GO
CREATE DATABASE [Test-117]
GO
CREATE DATABASE [Test-118]
GO
CREATE DATABASE [Test-119]
GO
CREATE DATABASE [Test-120]
GO
CREATE DATABASE [Test-121]
GO
CREATE DATABASE [Test-122]
GO
CREATE DATABASE [Test-123]
GO
CREATE DATABASE [Test-124]
GO
CREATE DATABASE [Test-125]
GO
CREATE DATABASE [Test-126]
GO
CREATE DATABASE [Test-127]
GO
CREATE DATABASE [Test-128]
GO
CREATE DATABASE [Test-129]
GO
CREATE DATABASE [Test-130]
GO
CREATE DATABASE [Test-131]
GO
CREATE DATABASE [Test-132]
GO
CREATE DATABASE [Test-133]
GO
CREATE DATABASE [Test-134]
GO
CREATE DATABASE [Test-135]
GO
CREATE DATABASE [Test-136]
GO
CREATE DATABASE [Test-137]
GO
CREATE DATABASE [Test-138]
GO
ALTER DATABASE [Test-001] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-002] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-003] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-004] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-005] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-006] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-007] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-008] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-009] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-010] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-011] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-012] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-013] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-014] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-015] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-016] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-017] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-018] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-019] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-020] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-021] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-022] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-023] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-024] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-025] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-026] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-027] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-028] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-029] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-030] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-031] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-032] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-033] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-034] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-035] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-036] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-037] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-038] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-039] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-040] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-041] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-042] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-043] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-044] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-045] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-046] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-047] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-048] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-049] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-050] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-051] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-052] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-053] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-054] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-055] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-056] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-057] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-058] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-059] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-060] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-061] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-062] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-063] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-064] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-065] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-066] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-067] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-068] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-069] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-070] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-071] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-072] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-073] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-074] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-075] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-076] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-077] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-078] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-079] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-080] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-081] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-082] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-083] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-084] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-085] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-086] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-087] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-088] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-089] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-090] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-091] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-092] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-093] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-094] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-095] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-096] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-097] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-098] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-099] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-100] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-101] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-102] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-103] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-104] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-105] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-106] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-107] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-108] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-109] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-110] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-111] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-112] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-113] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-114] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-115] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-116] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-117] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-118] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-119] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-120] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-121] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-122] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-123] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-124] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-125] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-126] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-127] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-128] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-129] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-130] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-131] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-132] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-133] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-134] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-135] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-136] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-137] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Test-138] SET RECOVERY SIMPLE
GO