name: packages

on:
  push:
    branches: [ "master" ]
    tags: ['\d+.\d+.\d']
    paths-ignore:
      - 'Upgradier.png'
      - 'xunit.runner'
      - '.editorconfig'
      - 'src/Example/**'

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # error if tag not exists in main
    # - name: tag in main
    #   run: git branch -a --contains "${{github.ref_name}}" | grep '.*/master$' 
    - name: dotnet-install
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: dotnet-restore
      run: dotnet restore

    - name: dotnet-build
      run: dotnet build -c Release --no-restore

    - name: dotnet-test
      run: dotnet test -c Release -p:CollectCoverage=true -p:CoverletOutput=coverage-results/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal

    - name: upload-coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: tests/Upgradier.Tests/coverage-results/coverage.opencover.xml
        verbose: true

    - name: package
      run: dotnet nuget push --api-key ${{secrets.NUGET}} --skip-duplicate --source https://api.nuget.org/v3/index.json artifacts/*.nupkg

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          generate_release_notes: true
          files: |
            artifacts/*
